echo opening Downloads folder...
cd ~/Downloads
echo cloning bedrocksync git repository...
git clone https://github.com/yutencurso/bedrocksync.git
echo opening bedrocksync folder...
cd ~/Downloads/bedrocksync
echo configuring bedrocksync command...
chmod +x dist/bedrocksync
sudo mv dist/bedrocksync /usr/local/bin/
echo bedrocksync installed